### PR TITLE
First pull request attempt

### PR DESCRIPTION
**Pull request by landtanin**

### CODE REVIEW

**Comment by ryan-shaw** [comment]
Some Git tips :) You may want to clean this one up and rebase.

`git rm --cached vendor/`

`find - name '.DS_Store' -exec git rm {} \;`

Commit then rebase 3 previous commits

`git rebase -i HEAD~3` - change latest to `squash`

**Comment by landtanin** [comment]
Hi, Ryan. I've tried "git rm --cached pathToVendor/" but it said "fatal: not removing '...../vendor' recursively without -r". Do u know what it means? Thanks in advance.

**Comment by ryan-shaw** [comment]
My bad, try this: `git rm -r --cached vender`

Then you'll also want to ignore those files:

`echo ".DS_Store >> .gitignore`
`echo "vendor/" >> .gitignore`

**Comment by landtanin** [comment]
I fixed it. I type "git rm -r -cached vendor" :dancing_men:

**Comment by landtanin** [comment]
landtanins-MacBook-Pro:HackSocNotts.github.io landtanin$ echo ".DS_Store > .gitignore

> echo "vendor/" >> .gitignore

I stuck here

**Comment by landtanin** [comment]
`
landtanins-MacBook-Pro:HackSocNotts.github.io landtanin$ echo ".DS_Store > .gitignore

> echo "vendor/" >> .gitignore
> 
> `

**Comment by landtanin** [comment]
There are the ">" signs and I can't leave it

**Comment by landtanin** [comment]
Solved. I typed `echo '.DS_Store' >> .gitignore` and `echo 'vendor/' >> .gitignore`

**Comment by landtanin** [comment]
Now I have to commit >> rebase 3 previous commits >> change the latest to `squash` >> and then push, right?

**Comment by jamietanna** [comment]
@landtanin once you've done that, could you commit and push up to this branch? Just to confirm that the right things are removed. Then we can guide you through a rebase (which will make sure there is only a single commit to merge )

**Comment by landtanin** [comment]
Can u see my latest commit? I don't have to do the pull request again, right?

**Comment by jamietanna** [comment]
Thanks @landtanin, yes I can see it. I'll have to look at this this  evening if that's okay?

**Comment by ryan-shaw** [comment]
Re-run `find . -name '.DS_Store' -exec git rm --cached {} \;` as you committed a couple more of those. Then commit again. Then rebase.

**Comment by landtanin** [comment]
Yeah. Thank you @jamietanna and @ryan-shaw . I'll wait till u guys confirm that my previous commit is all correct.

**Comment by ryan-shaw** [comment]
It is correct, you just need to remove the extra `.DS_Store` files.

You may also want to remove `.bundle/config`

**Comment by landtanin** [comment]
Thanks @ryan-shaw , I deleted it. So far I've done 4 commits. I have to rebase to the fist one, right?

**Comment by landtanin** [comment]
Hey, @ryan-shaw . I rebase the last 4 commits (which all my commit) and change the latest one to `squash` already. Then I pushed it.

**Comment by jamietanna** [comment]
@landtanin it may be worth squashing all commits except the last one, so there is a single one. So the first commit should be `pick`, and the others should be `squash`

**Comment by landtanin** [comment]
So `squash` the first 3 commits and `pick` the latest one, right?

**Comment by ryan-shaw** [comment]
Yes, in interactive rebase they appear in descending order oldest -> newest. So the top line will be `pick` (or `p`) and the next 3 lines will be `squash` (or `s`)

**Comment by landtanin** [comment]
Now before I push, do I have to pull first?

**Comment by landtanin** [comment]
I've done the squashing. But I can't push now. It told me to pull first

**Comment by ryan-shaw** [comment]
Rebasing, rewrites your commit history which means it will be out of sync with the remote repo. You have to overwrite the remote with your local changes using `git push --force` (or `git push -f`)

You may also want to rebase onto master as there are changes: `git rebase master` when you hit a conflict, fix it up then `git rebase --continue`.

Or simply merge: `git fetch` -> `git merge origin/master` -> fix conflicts -> commit.

**Comment by landtanin** [comment]
I did `git push --force`. Is everything alright?

**Comment by jamietanna** [comment]
Looks like there's still `img/.DS_STORE`. Should be all good once that's removed.

**Comment by landtanin** [comment]
I tried the command `find . -name '.DS_Store' -exec git rm --cached {} \;` but still could not find img/.DS_Store. When I type `git status` afterward, there's nothing shown. Do u have any advice?_

**Comment by jamietanna** [comment]
My apologies, @landtanin, it looks like the file was one that you deleted, that had been added previously. All looks good, once you've resolved the conflicts.

To do this cleanly, so the history remains nice, I would recommend the following:

```
git remote add upstream git@github.com:hacksocnotts/HackSocNotts.github.io.git
git fetch upstream
git rebase upstream/master
```

At which point there will be some conflicts, which which you will [need to resolve](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/#creating-an-edit-collision).

Once that's done, run `git rebase --continue`, followed by a `git push --force`. This _should_ then be ready to merge nicely.

**Comment by jamietanna** [comment]
Great job, thanks @landtanin!

**Comment by landtanin** [comment]
Thanks a lot, guys @ryan-shaw @jamietanna 👍

**Pull request merged**
